---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nusrlrsu/nusrah-app/
    - /bin/cp -R * $DEPLOYPATH
    - source /home/nusrlrsu/nodevenv/nusrah-app/20/bin/activate
    - cd $DEPLOYPATH
    - rm -rf node_modules
    - npm ci --include=dev
    - npx prisma generate
    - npm run build
    - touch $DEPLOYPATH/tmp/restart.txt
